import '@/styles/home.scss'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { abrilFatface, helvetica } from './font'
import './globals.css'

// const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang='en'>
			<body className={`font-helvetica ${helvetica.variable} ${abrilFatface.variable}`}>
				{children}
			</body>
		</html>
	)
}
